EasyBrizy/Brizy-Local-Editor

packages/core/public/index.html
packages/core/src/actions/save.ts
packages/core/src/core.ts
packages/core/src/types/types.ts
packages/demo/public/index.html

get output in save method

---

packages/core/public/index.html
packages/core/src/actions/save.ts
packages/core/src/core.ts
packages/core/src/types/types.ts

Refactor logic for get output in callback by `Update`

refactor(core): refactor logic for get output in callback

---

packages/core/docs/cdn.MD
packages/core/docs/self-hosted.MD
packages/core/public/index.html
packages/core/src/types/types.ts
packages/core/src/utils/createOutput.ts

* Added Popup positions to export

Added popup positions to export

---

packages/core/docs/cdn.MD
packages/core/docs/self-hosted.MD

* Added ```--light-gray``` as variable for Theme interface in docs

refactor : Updated docs theme interface

---

packages/core/docs/rendering-popup.MD

Related to : https://github.com/bagrinsergiu/MoE-Support/issues/64
* Added docs for rendering partial popup

feat(docs) : Added docs for rendering partial popup

---

package-lock.json
packages/core/package.json
packages/core/src/actions/init.ts

- fix: Core encoded pageData to base64

fix(core): encode pageData

---

packages/core/docs/cdn.MD
packages/core/docs/self-hosted.MD
packages/core/src/types/dynamicContent.ts

added docs for DCHandler placeholder property

feat(docs): Added docs for DCHandler placeholder property

---

packages/core/docs/rendering-popup.MD

| Q  | A |
| Screenshot  | N/ A|
| Related tickets	  | https://github.com/bagrinsergiu/MoE-Support/issues/78 |
Sequential script load for popup rendering 
* Refactor: Updated popup rendering docs

refactor(popupDocs):  Updated popup rendering docs

---

packages/core/docs/cdn.MD
packages/core/docs/self-hosted.MD
packages/core/src/actions/autoSave.ts
packages/core/src/actions/index.ts
packages/core/src/actions/types.ts
packages/core/src/core.ts
packages/core/src/types/types.ts

| Q  | A |
| Screenshot  | N/A|
| Related tickets	  | https://github.com/bagrinsergiu/MoE-Support/issues/92 |
[Screencast from 04-30-2024 03:52:56 PM.webm](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/40203375/729207ac-fe16-466e-8efe-04665bfbfde7)
[Screencast from 04-30-2024 03:53:40 PM.webm](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/40203375/9133ea55-39c8-44ec-a77a-e2a0f7b23c4d)
* New: added config onAutoSaveInterval
* New: added autoSave

feat(autoSave): added autoSave and autoSave interval

---

packages/core/public/index.html
packages/core/src/actions/init.ts
packages/core/src/types/types.ts

| Q  | A |
| Screenshot  | N/A |
| Related tickets	  | https://github.com/bagrinsergiu/MoE-Support/issues/95 |
[Screencast from 05-09-2024 02:53:52 PM.webm](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/40203375/e1be6c80-dd80-4810-b9b5-76d9960c4c4b)
[Screencast from 05-09-2024 02:54:31 PM.webm](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/40203375/9c2ee000-fc98-4ac5-a699-ea6ff0a25b27)
* Fixed: missing autoSaveInterval in config

fix(config): missing autoSaveInterval in config

---

packages/create-brizy-thirdparty/package.json
packages/create-brizy-thirdparty/templates/src/Counter/export.ts
packages/create-brizy-thirdparty/templates/src/Counter/index.scss
packages/create-brizy-thirdparty/templates/src/Counter/index.tsx
packages/create-brizy-thirdparty/templates/src/Map/Editor/index.tsx
packages/create-brizy-thirdparty/templates/src/Map/View/index.tsx
packages/create-brizy-thirdparty/templates/src/Map/index.scss
packages/create-brizy-thirdparty/templates/src/Map/index.tsx
packages/create-brizy-thirdparty/templates/src/Map/types.ts
packages/create-brizy-thirdparty/templates/src/index.editor.ts
packages/create-brizy-thirdparty/templates/src/index.ts
packages/create-brizy-thirdparty/templates/src/index.view.ts

update thirdparty starter template to the new format

fix(create-script): update thirdparty starter template to the new format

---

docusaurus/docs-internals/editor-controls/data-controls/inputText.md

https://github.com/bagrinsergiu/blox-editor/issues/26569

26569 input text

---

docusaurus/docs-internals/editor-controls/data-controls/textarea.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26568

More props for textarea

---

docusaurus/docs-internals/editor-controls/ui-controls/button.md

https://github.com/bagrinsergiu/blox-editor/issues/26574

fix(button): add Parameters

---

docusaurus/docs-internals/editor-controls/multivalue-controls/corners.md

https://github.com/bagrinsergiu/blox-editor/issues/26576

26576 corners

---

docusaurus/docs-internals/editor-controls/multivalue-controls/box-shadow.md

https://github.com/bagrinsergiu/blox-editor/issues/26594

fix(boxShadow): add

---

docusaurus/docs-internals/editor-controls/data-controls/radiogroup.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26608

Docs Extend for RadioGroup

---

docusaurus/docs-internals/editor-controls/multivalue-controls/iconsPicker.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26602

26559 icons picker v2

---

docusaurus/docs-internals/editor-controls/data-controls/colorPicker.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26577

extent docs

---

docusaurus/docs-internals/editor-controls/data-controls/editableSelect.md

Related issue https://github.com/bagrinsergiu/blox-editor/issues/26591

editable select docs

---

docusaurus/docs-internals/editor-controls/data-controls/paypal.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26616

Added more docs

---

docusaurus/docs-internals/control-arguments/css.md
docusaurus/docs-internals/control-arguments/dynamic-content.md

Added documentation for CSS control

Added docs for CSS

---

packages/core/src/core.ts
packages/core/src/types/templates.ts
packages/demo-nextjs/src/components/Editor/index.tsx
packages/demo-nextjs/src/components/Editor/utils.ts
packages/demo-react/src/Editor.tsx
packages/demo-react/src/utils.ts
packages/demo/public/index.html

https://github.com/bagrinsergiu/blox-editor/issues/26729

fix(demo): loading templates, kits

---

docusaurus/docs-internals/editor-controls/data-controls/toggle-button.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26642

toggle button extent

---

docusaurus/docs-internals/editor-controls/data-controls/toggle.md

https://github.com/bagrinsergiu/blox-editor/issues/26645

feat(toggle): add parameters

---

docusaurus/docs-internals/editor-controls/data-controls/iconSetter.md

https://github.com/bagrinsergiu/blox-editor/issues/26648

feat(iconSetter): add parameters

---

docusaurus/docs-internals/editor-controls/data-controls/border.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26651

added border more docs

---

packages/demo-nextjs/src/components/Metronic/assets/sass/core/components/_variables.scss
packages/demo-nextjs/src/components/Metronic/assets/sass/layout/_variables.custom.scss
packages/demo-nextjs/src/components/Metronic/layout/components/sidebar/sidebar-menu/SidebarMenuItem.tsx
packages/demo-nextjs/src/components/Metronic/layout/components/sidebar/sidebar-menu/SidebarMenuMain.tsx

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26940
Changed color for sidebar and used outlined icons

[METRONIC CMS] Sidebar ui fixes

---

packages/demo-nextjs/src/app/admin/(cms)/leads/page.tsx
packages/demo-nextjs/src/app/admin/(cms)/system/page.tsx
packages/demo-nextjs/src/components/Metronic/modules/apps/collections/CollectionsList.tsx
packages/demo-nextjs/src/components/Metronic/modules/apps/collections/components/pagination/Pagination.tsx
packages/demo-nextjs/src/components/Metronic/modules/apps/collections/components/pagination/types.ts
packages/demo-nextjs/src/components/Metronic/modules/apps/collections/table/CollectionsTable.tsx
packages/demo-nextjs/src/components/Metronic/modules/apps/collections/table/columns/CollectionActionsCell.tsx
packages/demo-nextjs/src/components/Metronic/modules/apps/collections/table/columns/_columns.tsx
packages/demo-nextjs/src/components/Metronic/modules/apps/collections/types.ts

* Improved: UI of pagination component
* Refactor: Disabled some fields of CollectionList component

refactored collectionlist and pagination components

---

README.MD
netlify.toml

- feat(docs): add deploy button to netlify

feat(docs): add deploy button to netlify

---

demo/html/public/index.html
demo/react/src/Editor.tsx
packages/core/src/types/templates.ts

| Q  | A |
| Screenshot  | ![2024-08-30_11-35](https://github.com/user-attachments/assets/20ccd36c-9dc1-4188-8f90-0a5a25cdf68f) |
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/389 |
[Screencast from 08-30-2024 01:29:21 PM.webm](https://github.com/user-attachments/assets/0744360a-e42a-4ee4-b65e-a1122c6c56f1)
[Screencast from 08-30-2024 01:35:12 PM.webm](https://github.com/user-attachments/assets/6fadcaca-57e4-4d39-b559-029d76b9262b)

fix(config): defaultPopup getMeta bug

---

demo/html/public/index.html
demo/nextjs-contenful/src/components/Editor/converters.ts
demo/nextjs-contenful/src/components/Editor/index.tsx
demo/react/src/Editor.tsx
demo/react/src/converters.ts
packages/core/src/core.ts
packages/core/src/types/templates.ts

Related issue: https://github.com/EasyBrizy/Brizy-Local-Editor/issues/452

Blocks for all

---

demo/html/public/index.html
demo/nextjs-contenful/src/components/Editor/index.tsx
demo/react/src/Editor.tsx
demo/react/src/converters.ts
packages/core/src/actions/index.ts
packages/core/src/actions/templates.ts
packages/core/src/actions/types.ts
packages/core/src/builderProvider/handlers/api/index.ts
packages/core/src/builderProvider/handlers/api/templates/stories.ts
packages/core/src/core.ts
packages/core/src/types/templates.ts
packages/demo-nextjs/src/components/Editor/contexts/converters.ts
packages/demo-nextjs/src/components/Editor/contexts/utils.ts

Related issue: https://github.com/EasyBrizy/Brizy-Local-Editor/issues/445

Story API for all demo

---

README.MD

| Q  | A |
| Screenshot  | N/A |
| Related tickets	  | https://github.com/bagrinsergiu/blox-editor/issues/27346 |
* New:  changed readme urls to use brizy documentation

refactor(readme): changed readme urls to use brizy documentation

---

docusaurus/docs/getting-started/brizy-config.md

Related issue: https://github.com/bagrinsergiu/blox-editor/issues/28422

Docs for isRTL

---

packages/demo-nextjs/src/widgets/Gallery/Components/BigImage/index.tsx
packages/demo-nextjs/src/widgets/Gallery/index.scss

https://github.com/bagrinsergiu/blox-editor/issues/29158

fix(gallery): some styles
